const cfg = window.RD_CONFIG;
let bundledSheets;
async function localSheets() {
  if (!bundledSheets) bundledSheets = fetch('data/sheets.json', { cache: 'no-store' })
    .then(response => response.ok ? response.json() : Promise.reject(Error('No synced Sheet snapshot is available yet.')));
  return bundledSheets;
}
const csv = async tab => {
  try {
    const sheets = await localSheets();
    if (Array.isArray(sheets[tab])) return sheets[tab];
  } catch { /* A direct public-Sheet fallback is kept for first-time setup. */ }
  if (!cfg.sheetId || cfg.sheetId.startsWith('PASTE_')) throw Error('Configure config.js with the published Google Sheet ID.');
  const root = cfg.sheetId.startsWith('2PACX-') ? `https://docs.google.com/spreadsheets/d/e/${cfg.sheetId}` : `https://docs.google.com/spreadsheets/d/${cfg.sheetId}`;
  const url = cfg.sources?.[tab] || `${root}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}`;
  const response = await fetch(url);
  if (!response.ok) throw Error('The department archive could not be reached.');
  const text = await response.text();
  if (/Page Not Found|Sign in to your Google Account/.test(text)) throw Error('Publish the Google Sheet to the web, then reload this page.');
  return parseCsv(text);
};
function parseCsv(s) { const rows=[]; let row=[], cell='', quote=false; for(let i=0;i<s.length;i++){let c=s[i]; if(c==='"'){if(quote&&s[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c} row.push(cell.trim()); if(row.some(Boolean))rows.push(row); const heads=rows.shift().map(x=>x.toLowerCase().replace(/[^a-z0-9]/g,'')); return rows.map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]||'']))); }
const esc = s => String(s||'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const date = d => d ? new Date(d).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}) : 'UNDATED';
function error(el,e){el.innerHTML=`<p class="loading">${esc(e.message)}</p>`}
async function home(){const el=document.querySelector('#announcements');if(!el)return;try{let a=await csv(cfg.tabs.announcements);el.innerHTML=a.slice(0,3).map(x=>`<article class="card"><small>${date(x.date)}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></article>`).join('')||'<p class="loading">No announcements recorded.</p>';document.querySelector('#sync').textContent='LIVE';}catch(e){error(el,e)}}
async function logs(){const el=document.querySelector('#logs');if(!el)return;try{let r=await csv(cfg.tabs.tests);el.innerHTML=r.map(x=>`<a class="log" href="scp.html?id=${encodeURIComponent(x.scpid)}"><span>${esc(x.scpid)}</span><strong>${esc(x.title)}</strong><small>${date(x.date)} · ${esc(x.status||'FILED')}</small><b>→</b></a>`).join('')||'<p class="loading">No test logs recorded.</p>'}catch(e){error(el,e)}}
async function file(){const el=document.querySelector('#scp-file');if(!el)return;try{let id=new URLSearchParams(location.search).get('id');let r=await csv(cfg.tabs.scps);let x=r.find(v=>v.scpid===id);if(!x)throw Error('This SCP file was not found.');document.title=`${x.scpid} | Research Department`;el.innerHTML=`<p class="eyebrow">${esc(x.classification||'RESTRICTED FILE')}</p><h1>${esc(x.scpid)} <em>${esc(x.title)}</em></h1><div class="metadata"><span>OBJECT CLASS <b>${esc(x.objectclass)}</b></span><span>RISK LEVEL <b>${esc(x.risklevel)}</b></span><span>STATUS <b>${esc(x.status)}</b></span></div><section><h2>Special Containment Procedures</h2><p>${esc(x.containment).replace(/\n/g,'<br>')}</p></section><section><h2>Description</h2><p>${esc(x.description).replace(/\n/g,'<br>')}</p></section><section><h2>Research Notes</h2><p>${esc(x.notes).replace(/\n/g,'<br>')}</p></section>`}catch(e){error(el,e)}}
async function roster(){const el=document.querySelector('#roster');if(!el)return;try{let [people,ranks]=await Promise.all([csv(cfg.tabs.roster),csv(cfg.tabs.ranks)]);let order=Object.fromEntries(ranks.map((x,i)=>[x.rank,i]));people.sort((a,b)=>(order[a.rank]??999)-(order[b.rank]??999)||a.robloxusername.localeCompare(b.robloxusername));let groups={};people.forEach(p=>(groups[p.rank]??=[]).push(p));el.innerHTML=Object.entries(groups).map(([rank,ps])=>`<section class="rank"><h2>${esc(rank)}</h2><div class="people">${ps.map(p=>`<a class="person" href="${esc(p.robloxprofileurl)}" target="_blank" rel="noreferrer"><img src="https://thumbnails.roblox.com/v1/users/avatar-headshot?userIds=${esc(p.robloxuserid)}&size=150x150&format=Png&isCircular=false" onerror="this.classList.add('missing')"><span><strong>${esc(p.robloxusername)}</strong><small>${esc(p.discordusername)}</small></span></a>`).join('')}</div></section>`).join('')||'<p class="loading">No personnel recorded.</p>'}catch(e){error(el,e)}}
async function archive(){const el=document.querySelector('#scp-archive');if(!el)return;try{let r=await csv(cfg.tabs.scps);el.innerHTML=r.map(x=>`<a class="log" href="scp.html?id=${encodeURIComponent(x.scpid)}"><span>${esc(x.scpid)}</span><strong>${esc(x.title)}</strong><small>${esc(x.objectclass||'UNCLASSIFIED')} · ${esc(x.status||'ON FILE')}</small><b>→</b></a>`).join('')||'<p class="loading">No object files recorded.</p>'}catch(e){error(el,e)}}
async function dashboard(){const el=document.querySelector('#metrics');if(!el)return;try{let [scps,people,tests]=await Promise.all([csv(cfg.tabs.scps),csv(cfg.tabs.roster),csv(cfg.tabs.tests)]);let total=scps.length, contained=scps.filter(x=>/contain/i.test(x.status)).length, breached=scps.filter(x=>/breach/i.test(x.status)).length;el.innerHTML=[[total,'TOTAL SCP FILES'],[contained,'CONTAINED'],[breached,'BREACHED'],[people.length,'PERSONNEL'],[tests.length,'TESTS CONDUCTED']].map(([n,l])=>`<div class="metric"><strong>${n}</strong><small>${l}</small></div>`).join('');document.querySelector('#sync').textContent='LIVE / SYNCHRONIZED'}catch(e){el.innerHTML=`<div class="metric error-metric">${esc(e.message)}</div>`;let s=document.querySelector('#sync');if(s)s.textContent='OFFLINE'}}
function account(){const button=document.querySelector('#account'), modal=document.querySelector('#login-modal'), clearance=document.querySelector('#user-clearance');let active=JSON.parse(localStorage.getItem('rdUser')||'null');const draw=()=>{if(active){button.textContent=`${active.username} / SIGN OUT`;if(clearance)clearance.textContent=`${active.rank} · ${active.clearancelevel||'LEVEL 1'}`}else{button.textContent='IDENTIFY';if(clearance)clearance.textContent='GUEST ACCESS'}};draw();if(!button||!modal)return;button.onclick=()=>{if(active){localStorage.removeItem('rdUser');active=null;draw();return}modal.classList.remove('hidden');modal.innerHTML=`<div class="login-box"><button class="close" aria-label="Close">×</button><p class="eyebrow">PERSONNEL AUTHENTICATION</p><h2>Identify yourself</h2><form id="login-form"><input name="username" placeholder="Username" required autocomplete="username"><input name="password" type="password" placeholder="Password" required autocomplete="current-password"><button class="button">Access archive <b>→</b></button><p id="login-error"></p></form></div>`;modal.querySelector('.close').onclick=()=>modal.classList.add('hidden');modal.querySelector('form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),err=modal.querySelector('#login-error');try{let users=await csv(cfg.tabs.users);let user=users.find(u=>u.username===f.get('username')&&u.password===f.get('password'));if(!user)throw Error('Credentials not recognized.');active=user;localStorage.setItem('rdUser',JSON.stringify(user));modal.classList.add('hidden');draw()}catch(x){err.textContent=x.message}}}}
home();logs();file();roster();archive();dashboard();account();
